#!/bin/sh
set -e

# We cannot change the packages user/group as it may install user/group specific files/directories across the filesystem
# what we can do is ensure a container user is created with a specific default container user and add the package user
# to the container group if needed.
name="_container"

if [ -n "$USERID" ]; then
    [ -z "$WORKDIR" ] && WORKDIR=/tmp
    getent passwd $name > /dev/null 2>&1 && deluser $name
    getent group $name > /dev/null 2>&1 && delgroup $name
    [ -n "$GROUPID" ] && [ "$USERID" -ne "$GROUPID" ] && addgroup -g $GROUPID $name
    adduser -D -g 'Container user' ${GROUPID:+-G $name} -h $WORKDIR -s /sbin/nologin -u $USERID $name
    chown root:$name $WORKDIR
fi

[ -n "$GROUPADD" ] && addgroup $GROUPADD $name

# We need to modify the permissions to allow read by the group if not already set
find "$WORKDIR" -type f -exec chmod 644 {} + &
find "$WORKDIR" -type d -exec chmod 755 {} + &
wait
