#!/bin/sh
set -e

stch_dir "${STCH_DIR:-"/etc"}" || exit 1

# Ensure stdout and stderr are writable as anyone due to some applications not logging to stdout and stderr.
# We can't chown as we don't know the specific user the application might run as.
chmod o+w /proc/self/fd/1 /proc/self/fd/2

exec "$@"
