#!/bin/sh

find "$@" -depth -name "*.stch" | while read -r f; do
    dir="${f%/*}"
    bname="${f%.*}"
    if [ -w "$dir" ]; then
        printf "Templating stch file %s..." "$f"
        # Overwriting on failure is intended
        if stch < "$f" > "$bname"; then
            echo "done"
        else
            echo "failed! for $f" >&2
            exit 1
        fi
    fi
done
