#!/bin/sh
stch() {
# -e add escapes to ``, -e add escapes to POSIX $vars (allow ${var})
val=$(eval "cat << EOF_\$PPID
$(set -e; sed -e 's:$[[:alpha:]_][[:alnum:]_]*:\\&:g' -e 's:`\(.*\)`:\\`\1\\`:g')
EOF_\$PPID")
[ "$val" ] && printf "%s\n" "$val"
}

stch
